project:
  type: website
  output-dir: docs

  

website:
  title: "Kevin A. Carson"
  navbar:
    background: "blue"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: stats_blog.qmd
        text: Stats Blog
    right:
      - icon: envelope
        href: mailto:kacarson@arizona.edu
      - text: CV
        href: https://www.dropbox.com/scl/fi/db7qnfl7tyubvuxr6w00t/Carson_CV_2025.pdf?rlkey=ovxaqbk2t28wy1puw1iwb9fe2&dl=0
      - icon: github
        href: https://github.com/kevinCarson
      - text: "<img src='images/ORCID-iD_icon_24x24.png' alt='ORCID' style='height:20px; vertical-align:middle;'>"
        href: https://orcid.org/0009-0001-5762-2586

  announcement: 
    content: "**News** - Check out the new R package dream for large relational event analysis and modeling! (07-18-2025)" 
    position: below-navbar 
    
  page-footer: 
    center: "Copyright 2025, Kevin A. Carson" 
    right: "Made with [R](https://cran.r-project.org/) and [Quarto](https://quarto.org/)"
    left: 
      - icon: envelope
        href: mailto:kacarson@arizona.edu
      - text: CV
        href: https://www.dropbox.com/scl/fi/db7qnfl7tyubvuxr6w00t/Carson_CV_2025.pdf?rlkey=ovxaqbk2t28wy1puw1iwb9fe2&dl=0
      - icon: github
        href: https://github.com/kevinCarson
      - text: "<img src='images/ORCID-iD_icon_24x24.png' alt='ORCID' style='height:20px; vertical-align:middle;'>"
        href: https://orcid.org/0009-0001-5762-2586

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

