project:
  type: website
  output-dir: docs

  

website:
  title: "Kevin A. Carson"
  navbar:
    background: "royalblue"
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
    right:
      - icon: envelope
        href: mailto:kacarson@arizona.edu
      - text: CV
        href: CV_KevinCarson.pdf
      - icon: github
        href: https://github.com/kevinCarson
      - text: "<img src='images/ORCID-iD_icon_24x24.png' alt='ORCID' style='height:20px; vertical-align:middle;'>"
        href: https://orcid.org/0009-0001-5762-2586

    
  page-footer: 
    center: "Copyright 2025, Kevin A. Carson" 
    right: "Made with [R](https://cran.r-project.org/) and [Quarto](https://quarto.org/)"
    left: 
      - icon: envelope
        href: mailto:kacarson@arizona.edu
      - text: CV
        href: CV_KevinCarson.pdf
      - icon: github
        href: https://github.com/kevinCarson
      - text: "<img src='images/ORCID-iD_icon_24x24.png' alt='ORCID' style='height:20px; vertical-align:middle;'>"
        href: https://orcid.org/0009-0001-5762-2586

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

